modLoader = "javafml"
loaderVersion = "[2,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues_link}"

[[mods]]
modId = "cat_vision"
version = "${version}"
displayName = "CatVision"
authors = "${mod_author}"
description = "${mod_description}"
logoFile = "${mod_logo_file_path}"
displayURL = "${mod_homepage_link}"

[[dependencies.cat_vision]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "cat_vision.neoforge.mixins.json"

[[dependencies.cat_vision]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"
